Start by importing the pipeline file, here lies the function that automates the process to generate the different diagrams. 

After we need to define the parameters used:
- theory: 
- in_particles:

After indicating the parameters the program offers 2 option:

- **complete**: the program return all diagrams at the specified order that contribute to the process considered.
- **framework**: indicate the combination of initial canonical diagrams that contribute to the process at said order. With later the option of generating the final diagrams that comes from said canonical diagrams.

In [ ]:
from src.core.pipeline import *  # Import the file that calculates the diagrams

theory = "phi4" # The theory to calculate diagrams for, e.g., "phi4", "qcd", "qcd_gluons"
in_particles = [1, 0] # Number of incoming particles, for each type of particles
out_particles = [1, 0] # Number of outgoing particles, for each type of particles
order = 2 # The order of the perturbation theory to calculate diagrams

mode = "complete" # The mode to calculate diagrams, e.g., "complete" or "framework"

In [32]:
from src.can_diagrams.phi4.canonical_diagrams import can_points, can_connections, can_count
from src.transforms.concatenation import in_out_connections

order = 2

in_out_matrix = np.zeros((len(can_points), len(can_points[0]), len(can_connections[0][0]), 2), dtype=int)
for q in range(len(can_points)):
    for i in range(len(can_points[q])):
        for j in range(len(can_connections[q][i])):
            in_out_matrix[q][i][j][0] = len(np.trim_zeros(in_out_connections(can_connections[q][i])[j][0]))
            in_out_matrix[q][i][j][1] = len(np.trim_zeros(in_out_connections(can_connections[q][i])[j][1]))

def new_in_out_matrix(in_out_1, in_out_2):
    new_in_out = np.zeros((min(in_out_1[1], in_out_2[0]), 2), dtype=int)
    for i in range(1, min(in_out_1[1], in_out_2[0])+1):
        new_in_out[i-1][0] = in_out_1[0] + in_out_2[0] - i
        new_in_out[i-1][1] = in_out_1[1] + in_out_2[1] - i
    return new_in_out


for q in range(len(can_points)):
    for p in range(len(can_points)):
        for i in range(len(can_points[q])):
            for j in range(len(can_points[p])):
                points = np.zeros((len(can_points[q][i]) + len(can_points[p][j]), 2))
                points[:len(can_points[q][i])] = can_points[q][i]
                points[len(can_points[q][i]):] = can_points[p][j] + np.array([np.max(can_points[q][i])+1, 0])
                print(in_out_matrix[q][i][0], in_out_matrix[p][j][0])
                print(new_in_out_matrix(in_out_matrix[q][i][0], in_out_matrix[p][j][0]))
                



        

[2 2] [2 2]
[[3 3]
 [2 2]]
[2 2] [1 3]
[[2 4]]
[2 2] [3 1]
[[4 2]
 [3 1]]
[1 3] [2 2]
[[2 4]
 [1 3]]
[1 3] [1 3]
[[1 5]]
[1 3] [3 1]
[[3 3]
 [2 2]
 [1 1]]
[3 1] [2 2]
[[4 2]]
[3 1] [1 3]
[[3 3]]
[3 1] [3 1]
[[5 1]]
